<a href="https://colab.research.google.com/github/KimDongChan0908/Artificial-Intelligence-Programming/blob/main/Broadcasting_%EF%BC%86_Transpose_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Broadcasting이란 Numpy와 같은 배열 연산 라이브러리에서 다른 모양(shape)의 배열 간에 연산을 수행 할 수 있다.

In [2]:
#Example (BroadCcasting)

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])

result = a+b

print(result)

[[2 4 6]
 [5 7 9]]


배열 'a'의 크기가 (2,3)이고 배열 'b' 의 크기는 (3,)이다. 브로드캐스팅을 통해 'b'가 배열 'a'와 동일한 모양으로 확장되어 두 배열 간의 요소별 덧셈이 수행된다.

-----
하지만 여기서 Rule이 존재한다.

첫번째, 두 ndarray의 차원의 수(number of dimensions)가 같지 않을 경우, 적은 ndarray의 shape가 leading slde쪽(shape에서 왼쪽)으로 1로 padding된다.

if) A의 shape (3,4,1)이고, B의 shape가 (1,2)이면, B가 2차원에서 3차원으로 늘어나고 left side에 1이 추가되어 (1,1,2)로 padding된 shape이 됨

In [7]:
a = np.ones((3,4,1))
b = np.ones((1,2))
print(b)
print(c.shape)

[[1. 1.]]
(3, 4, 2)


두번째, shape에서 대응되는 값들이 일치하지 않을 경우, ndarray 각각에서 shape가 1인 차원이 상대방의 해당하는 차원의 shape로 변경된다.

세번째, 두번째 룰을 적용하라고 할때, shape가 일치하지 않으면서 어느 한 쪽 ndarray가 1이 아닌 경우엔 broadcasting이 실패함.

Transpose(전치) - m x n matrix A 가 존재한다고 했을 때 A의 전치행렬은 n x m (행과 열의 순서를 바꿔주는) matrix가 된다.  

---
Tensor에서의 transpose는 여러 축들 중 2개를 서로의 위치를 바꾸는 것을 의미한다.

In [3]:
import numpy as np
a = np.random.rand(3,4)

t1 = np.transpose(a)
t2 = a.T

print(a.shape)
print(t1.shape)
print(t2.shape)

t2[0,1] = 777
print(a[1,0])
print(t1[0,1])
print(t2[0,1])

(3, 4)
(4, 3)
(4, 3)
777.0
777.0
777.0


In [6]:
import torch
import tensorflow as tf

a_torch = torch.rand(2,3)

t1_torch = torch.transpose(a_torch, 0, 1)
t2_torch = a_torch.T

print(a_torch.shape)
print(t1_torch.shape)
print(t2_torch.shape)

torch.Size([2, 3])
torch.Size([3, 2])
torch.Size([3, 2])


In [7]:
a_tf = tf.random.normal([2,3])
t1_tf = tf.transpose(a_tf)
t2_tf = tf.transpose(a_tf, perm =[1,0]) #perm은 tensorflow의 tf.transpose() 함수에서 사용되는 매개변수 중 하나.
# Transpose 작업에서 차원의 순서를 지정 [1,0] 은 2차원 배열에서 첫번째 축과 두번째 축의 순서가 바뀐다.

print(a_tf.shape, a_tf.dtype)
print(t1_tf.shape, t1_tf.dtype)

indices = tf.constant([0,1])
updates = tf.constant([77], dtype = tf.float32)
t2_tf = tf.tensor_scatter_nd_update(t2_tf, indices, updates)

print(a_tf[1,0])
print(t1_tf[0,1])
print(t2_tf[0,1])

(2, 3) <dtype: 'float32'>
(3, 2) <dtype: 'float32'>


InvalidArgumentError: {{function_node __wrapped__TensorScatterUpdate_device_/job:localhost/replica:0/task:0/device:CPU:0}} Inner dimensions of output shape must match inner dimensions of updates shape. Output: [3,2] updates: [1] [Op:TensorScatterUpdate] name: 