<a href="https://colab.research.google.com/github/KimDongChan0908/Artificial-Intelligence-Programming/blob/Week-3-Class/Indexing_%2B_Vectorized_Operation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy나 pytorch, tensorflow의 텐서들도 파이썬의 list 또는 tuple에서의 indexing과 slicing이 거의 그대로 사용됨.
----
 (multi-dimension에서 대가로 안에서 comma로 구분하여 각 축에 대한 indexing과 slicing을 할 수 있음)

In [5]:
import numpy as np
a = np.arange(0,12).reshape(3,4)

print(a)
print('===============')
print(f'a[0] is"{a[0]}"')
print(f'a[0,2] is "{a[0,2]}"')
print(f'a[0][2] is "{a[0][2]}"')
print('--------------------')
print(f'a[1,2:] is "{a[1,2:]}"')
print(f'a[1,::2] is "{a[1,::2]}"')
print(f'a[1,::-1] is"{a[1,::-1]}"')
print(f'a[1,3:0:-1] is "{a[1,2:0:-1]}"') # negative step

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[0] is"[0 1 2 3]"
a[0,2] is "2"
a[0][2] is "2"
--------------------
a[1,2:] is "[6 7]"
a[1,::2] is "[4 6]"
a[1,::-1] is"[7 6 5 4]"
a[1,3:0:-1] is "[6 5]"
a[1,0::-1] is [7 6 5]"


In [7]:
#Pytorch 의 tensor (여기서는 negative step(-1)이 동작하지 않음)

import torch

a = np.arange(0,12).reshape(3,4)
a_torch = torch.tensor(a)

print(a_torch)
print(f'a_torch[0] is "{a_torch[0]}"')
print(f'a_torch[0,2] is "{a_torch[0,2]}"')
print(f'a_torch[0][2] is "{a_torch[0][2]}"')

print(f'a_torch[1,3:] is "{a_torch[1,3:]}"')
print(f'a_torch[1, ::2] is "{a_torch[1, ::2]}"')

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
a_torch[0] is "tensor([0, 1, 2, 3])"
a_torch[0,2] is "2"
a_torch[0][2] is "2"
a_torch[1,3:] is "tensor([7])"
a_torch[1, ::2] is "tensor([4, 6])"


In [9]:
import tensorflow as tf

a_tf = tf.constant(a)

print(a_tf)
print(f'a_tf[0] is "{a_tf[0]}"')
print(f'a_tf[0,2] is "{a_tf[0,2]}"')
print(f'a_tf[0][2] is "{a_tf[0][2]}')

print(f'a_tf[1,2:] is "{a_tf[1,2:]}"')
print(f'a_tf[1,::2] is "{a_tf[1, ::2]}"')
print(f'a_tf[1, ::-2] is "{a_tf[1, ::-2]}"')

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int64)
a_tf[0] is "[0 1 2 3]"
a_tf[0,2] is "2"
a_tf[0][2] is "2
a_tf[1,2:] is "[6 7]"
a_tf[1,::2] is "[4 6]"
a_tf[1, ::-2] is "[7 5]"


In [5]:
import numpy as np
import tensorflow as tf
import torch

x = np.array([100.,500.,300.,400])
x_torch = torch.tensor([100.,500.,300.,400,])
x_tf = tf.constant([100.,500.,300.,400.])

f_indices = [2,3,1] #Fancy Indexing

print('original')
print(x)
print('-----------')
print('numpy')
print(x[f_indices])
print('-----------')
print(x_torch[f_indices])
print('---------')
print('tensorflow')
print(tf.gather(x_tf, f_indices))

original
[100. 500. 300. 400.]
-----------
numpy
[300. 400. 500.]
-----------
tensor([300., 400., 500.])
---------
tensorflow
tf.Tensor([300. 400. 500.], shape=(3,), dtype=float32)


In [7]:
x = np.arange(5*5).reshape(5,5) * 10
x_torch = torch.arange(5*5).view(size=(5,5)) * 10
x_tf =tf.constant(x)

indices_0 = [0, 1, 2, 3]
indices_1 = [0, 1, 2, 3]

print('original: ')
print(x)
print('------------')
print('numpy: ')
b = x[indices_0, indices_1]
print('b.shape =',b.shape)
print(b)
print('---------')
print('torch:')
c = x_torch[indices_0, indices_1]
print('c.shape =',c.shape)
print(c)
print('-----------')
print('tensorflow')
d = tf.gather_nd(x_tf, [i for i in zip (indices_0, indices_1)])
print('d.shape =', d.shape)
print(d)

original: 
[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]
 [200 210 220 230 240]]
------------
numpy: 
b.shape = (4,)
[  0  60 120 180]
---------
torch:
c.shape = torch.Size([4])
tensor([  0,  60, 120, 180])
-----------
tensorflow
d.shape = (4,)
tf.Tensor([  0  60 120 180], shape=(4,), dtype=int64)


In [11]:
x = np.arange(3*3*3).reshape(3,3,3) * 10

print('original: ')
print(x)
print('-----------')
print('boolean mask:')
b = x <= 270/2

print(b.shape)
print(b)
print('----------')
print('x <= 135')
print(x[b])
print('----------')
print('----------')
print('x <= 135 | x >= 200')
b1 = b | (x >= 200)
print('----------')
print(b1)
print('----------')
print('boolean mask')
print(b1)
print('----------')
print(x[b1])
print('----------')
print(x[(x<= 300/2) | (x >= 200)])

original: 
[[[  0  10  20]
  [ 30  40  50]
  [ 60  70  80]]

 [[ 90 100 110]
  [120 130 140]
  [150 160 170]]

 [[180 190 200]
  [210 220 230]
  [240 250 260]]]
-----------
boolean mask:
(3, 3, 3)
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]]
----------
x <= 135
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130]
----------
----------
x <= 135 | x >= 200
----------
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False  True]
  [ True  True  True]
  [ True  True  True]]]
----------
boolean mask
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False  True]
  [ True  True  True]
  [ True  True  True]]]
----------
[  0  10  20  30  40  50 

In [16]:
x_torch = torch.arange(4*4*4).view(size = (4,4,4)) * 10
print('Original')
print(x_torch)
print('-----------------')

print(x_torch[(x_torch <= 300/2 ) | (x_torch >= 220 )])

print('---------------')

x_tf = tf.constant(x) # x 는 위에서 정의된  np.arange(3*3*3).reshape(3,3,3) * 10
print(x_tf[(x_tf <= tf.cast(270/2, tf.int64)) | (x_tf >= 250 )])

Original
tensor([[[  0,  10,  20,  30],
         [ 40,  50,  60,  70],
         [ 80,  90, 100, 110],
         [120, 130, 140, 150]],

        [[160, 170, 180, 190],
         [200, 210, 220, 230],
         [240, 250, 260, 270],
         [280, 290, 300, 310]],

        [[320, 330, 340, 350],
         [360, 370, 380, 390],
         [400, 410, 420, 430],
         [440, 450, 460, 470]],

        [[480, 490, 500, 510],
         [520, 530, 540, 550],
         [560, 570, 580, 590],
         [600, 610, 620, 630]]])
-----------------
tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330,
        340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470,
        480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610,
        620, 630])
---------------
tf.Tensor([  0  10  20  30  40  50  60  70  80  90 100 110 120 130 250 260], shape=(16,), dtype=int64)


In [17]:
#where 함수 : numpy 의 idx

import numpy as np

r = np.random.default_rng(seed = 32)

a = r.random((3,3,3)).astype(np.float32) * 10

bm = a>=5.
idxs = np.where(a>=5)

print(a)
print('-------------')
print(np.array(idxs).shape)
print(idxs)

[[[1.6024282  5.722295   3.7713554 ]
  [3.229352   6.8661394  9.722321  ]
  [9.668303   6.7129846  8.301016  ]]

 [[4.5971184  3.1707754  5.4255624 ]
  [6.0122337  9.130272   4.0845737 ]
  [5.5091596  4.104853   1.5238988 ]]

 [[0.4054205  2.3318279  6.077842  ]
  [9.048278   0.08684255 4.59207   ]
  [8.125638   9.617895   1.6119792 ]]]
-------------
(3, 14)
(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 1, 2, 2, 2, 0, 1, 1, 2, 0, 1, 2, 2]), array([1, 1, 2, 0, 1, 2, 2, 0, 1, 0, 2, 0, 0, 1]))


----------- Vector Operation ------------

In [19]:
def add_vectors(x,y):
  result = []
  for i in range(len(x)):
    result.append(x[i] + y[i])
  return result

x = np.array([11,22,33])
y = np.array([22,34,36])

z = add_vectors(x,y)

print(z)

import numpy as np #numpy 로 vector operation 하는 방안

z = np.add(x,y)

print(z)

[33, 56, 69]
[33 56 69]


In [4]:
# exponential
import torch
import tensorflow as tf
import numpy as np
a = np.arange(6).reshape((3,2)).astype(np.float32)

c = np.exp(a)

print(a)
print(c)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
[[  1.          2.718282 ]
 [  7.3890557  20.085537 ]
 [ 54.59815   148.41316  ]]


NaN safe functions 제공 -> Aggregations(집계) (NaN 사용시 -> None 값은 넘기고 계산을 하는 구조.)


In [18]:
d = np.mean(a, axis = 0) #axis 0으로 설정시 열의 평균을 내는것을 확인할 수 있음
print(d)
print('-----------')
e = np.mean(a, axis = 1) #axis 1으로 설정시 각 행의 평균을 내는 것
print(e)
a_t = torch.tensor(a).float()
print('-------------------')
c_t = torch.median(a_t, dim=1)
print(c_t)

[2. 3.]
-----------
[0.5 2.5 4.5]
-------------------
torch.return_types.median(
values=tensor([0., 2., 4.]),
indices=tensor([0, 0, 0]))
