<a href="https://colab.research.google.com/github/KimDongChan0908/Artificial-Intelligence-Programming/blob/Week-3-Class/Python_Data_Type_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
for c in [np, torch, tf]:
  print(c.__name__, c.__version__)

#numpy, torch, tensorflow의 version을 확인하는 습관을 들일것.

numpy 1.25.2
torch 2.2.1+cu121
tensorflow 2.15.0


"Unboxed type"은 컴퓨터 과학에서 사용되는 용어로, 메모리 상에서 추가적인 포인터나 래퍼(wrapper) 없이 값을 직접 저장하는 데이터 타입을 가리킵니다.

----

Python에서는 기본 numeric type 들도 모조리 object 이기 때문에 reference count와 같은 meta data 및 자신의 type에 따른 method를 제공한다.

In [2]:
import tensorflow as tf
import torch
import numpy as np

t = (1,2,3,4)

a = np.array(t)

tensor = tf.constant(t)

p = torch.tensor(t)

print(a.ndim)
print(a.shape)
print(a.itemsize)
print(a.size)
print(a.dtype)

print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.dtype)

print(p.ndim)
print(p.shape)
print(p.itemsize)
print(p.size())
print(p.dtype)

1
(4,)
8
4
int64
tf.Tensor(1, shape=(), dtype=int32)
1
<dtype: 'int32'>
1
torch.Size([4])
8
torch.Size([4])
torch.int64


attribute란, dtyoe, ndim, shape 등이 있음.

torch, numpy에선 지원하는 것들로는 itemsize(element 하나가 차지하는 bytes 크기), size or size() : numpy는 그냥 attribute로 pytorch에선 method로 전체 element를 반환함.

-----
Python의 Sequence Type 인 list, tuple을 통해 Tensor 인스턴스를 만드는 것이 가능함.

np.array, torch.tensor, tf_constant(tf.Variable)

In [5]:
import tensorflow as tf

t = (10,20,40,70)

a = np.array(t)
a_tf = tf.Variable(t)
a_torch = torch.tensor(t)

torch와 tensorflow의 tensor instance들은 numpy의 (ndarray n-dimension array) instance로 변환가능함.

In [6]:
a1_np = a_tf.numpy()
a2_np = a_torch.numpy()

※ torch의 경우 ndarray 인스턴스는 원래의 tensor와 connected된 상태임. -> cuda 환경에서 돌아가는지 확인해볼 필요가 있음 (cpu에서는 돌아가지만, gpu에서 동작하지 않음)

In [7]:
a2_np[3] = 789
print(a2_np)
print(a_torch)

[ 10  20  40 789]
tensor([ 10,  20,  40, 789])


※ tensorflow의 tensor인 tf.constant instance는 immutable(불변)이기 때문에, ndarray 인스턴스로 얻고나서 데이터를 변경시켜도 tensorflow의 tensor 인스터스에는 영향을 주지 않음!

In [8]:
print(a1_np)
print(a_tf)
a1_np[2] =789
print(a1_np)
print(a_tf)
#numpy에 대해서 copy본에 대해서 변경이 되고 기존 tf.tensor는 변경되지 않는다

[10 20 40 70]
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10, 20, 40, 70], dtype=int32)>
[ 10  20 789  70]
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10, 20, 40, 70], dtype=int32)>


In [12]:
print(a_torch)
a3_copy = a_torch.numpy().copy() #copy()를 써서 ndarray 인스턴스를 연결되지 않은상태로 얻어옴
a3_copy[2] = 190
print(a3_copy) #실행결과가 2번째 index가 190으로 변했지만, torch는 변하지않은것을 관찰할수 있음.
print(a_torch)

tensor([ 10,  20,  40, 789])
[ 10  20 190 789]
tensor([ 10,  20,  40, 789])


In [13]:
t = (100,200,300,400)

a = np.array(t)
a_tf = tf.constant(a)
a_torch = torch.tensor(a)

tf.convert_to_tensor와 torch.from_numpy를 이용할 수 있음.
numpy를 가지고, tensorflow와 tensor인스턴스를 얻을 수 있음

In [14]:
a_tf = tf.convert_to_tensor(a)
a_torch = torch.from_numpy(a)
print(a_tf)
print(a_torch)

tf.Tensor([100 200 300 400], shape=(4,), dtype=int64)
tensor([100, 200, 300, 400])


In [15]:
a_torch[1] = 239
print(a_torch)
print(a)

tensor([100, 239, 300, 400])
[100 239 300 400]


※ 바꾸는 원본 tensor인스턴스를 기반으로 원하는 dtpe로 구성된 새로운 tensor 인스턴스가 생성됨.

In [16]:
a = np.ones((3,3)) # 3 By 3 Matrix (1,1,1) ~ (1,1,1)
b = np.uint8(a)
c = a.astype('float32')

print(c)

print(id(a),a.dtype)
print(id(b),b.dtype)
print(id(c),c.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
133138122642448 float64
133138122642736 uint8
133138122646288 float32


In [19]:
a_torch = torch.rand(3,4)
b_torch = a_torch.to(torch.uint8) #torch.tensor.to(desired_dtype)
c_torch = a_torch.type(torch.float64)

print(b_torch)
print(c_torch)
print(id(a_torch), a_torch.dtype)
print(id(b_torch), b_torch.dtype)
print(id(c_torch), c_torch.dtype)

b_torch[0,1] = 9
c_torch [0,0] = 1000

print(a_torch)
print(b_torch)
print(c_torch)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)
tensor([[0.0060, 0.9311, 0.1067, 0.2873],
        [0.9065, 0.6115, 0.2931, 0.4839],
        [0.8441, 0.0527, 0.0032, 0.2181]], dtype=torch.float64)
133137879151168 torch.float32
133137879140368 torch.uint8
133137879141168 torch.float64
tensor([[0.0060, 0.9311, 0.1067, 0.2873],
        [0.9065, 0.6115, 0.2931, 0.4839],
        [0.8441, 0.0527, 0.0032, 0.2181]])
tensor([[0, 9, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)
tensor([[1.0000e+03, 9.3110e-01, 1.0673e-01, 2.8732e-01],
        [9.0655e-01, 6.1146e-01, 2.9311e-01, 4.8385e-01],
        [8.4408e-01, 5.2678e-02, 3.2336e-03, 2.1808e-01]], dtype=torch.float64)


In [21]:
a_tf = tf.random.uniform(shape=(3,4))
c_tf = tf.dtypes.cast(a_tf, tf.float64)

print(c_tf)
print(id(a_tf), a_tf.dtype)
print(id(c_tf), c_tf.dtype)

tf.Tensor(
[[0.15070462 0.49760282 0.90172756 0.90589976]
 [0.08941305 0.86534238 0.26071417 0.32211864]
 [0.953614   0.4076432  0.01153767 0.62054801]], shape=(3, 4), dtype=float64)
133138113723232 <dtype: 'float32'>
133138113719536 <dtype: 'float64'>


※ shape 는 tensor의 각 축의 크기를 나타내는 sequene type의 인스턴스임.(텐서의 형태를 지정하는데 사용)

----------------

numpy.reshape(numpy 모듈의 reshape 함수 이용) , numpy.numpy.array.reshape (numpy 의 ndarray인스턴스의 reshape 메서드를 이용하는 차이점이 존재)

torch.reshape(torch 모듈의 reshape 함수 이용), torch.tensor.reshape(tensor 인스턴스의 reshape 메서드 사용)

--------
인스턴스와 모듈의 차이
- 인스턴스 : 스턴스는 클래스(class)를 기반으로 생성된 객체(object)를 말합니다.

- 모듈 : 모듈은 파이썬에서 코드를 구성하는 단위입니다. 일반적으로 하나의 파일에 하나의 모듈이 정의됩니다.